<?php

$factory->define(App\Models\Tenant\SalesInvoiceContent::class, function (Faker\Generator $faker) {
    return [
        'sales_invoice_id' => $faker->name,
		'row_number' => $faker->name,
		'return_content_id' => $faker->name,
		'content_type' => $faker->name,
		'store_credit_id' => $faker->name,
		'product_sub_id' => $faker->name,
		'barcode' => $faker->name,
		'checkout_description' => $faker->name,
		'color_name' => $faker->name,
		'title' => $faker->name,
		'size' => $faker->name,
		'brand_name' => $faker->name,
		'style_number' => $faker->name,
		'color_code' => $faker->name,
		'retail_price' => $faker->name,
		'sale_price' => $faker->name,
		'sales_tax_category_id' => $faker->name,
		'local_tax_jurisdiction_id' => $faker->name,
		'local_regular_sales_tax_rate_id' => $faker->name,
		'local_exemption_sales_tax_rate_id' => $faker->name,
		'local_regular_tax_rate' => $faker->name,
		'local_exemption_tax_rate' => $faker->name,
		'local_exemption_value' => $faker->name,
		'state_tax_jurisdiction_id' => $faker->name,
		'state_regular_sales_tax_rate_id' => $faker->name,
		'state_exemption_sales_tax_rate_id' => $faker->name,
		'state_regular_tax_rate' => $faker->name,
		'state_exemption_tax_rate' => $faker->name,
		'state_exemption_value' => $faker->name,
		'tax_rate' => $faker->name,
		'tax_total' => $faker->name,
		'discount' => $faker->name,
		'discount_id' => $faker->name,
		'discount_type' => $faker->name,
		'applied_instore_discount' => $faker->name,
		'quantity' => $faker->name,
		'extension' => $faker->name,
		'special_order_id' => $faker->name,
		'alteration_id' => $faker->name,
		'special_order' => $faker->name,
		'paid' => $faker->name,
		'ship' => $faker->name,
		'promotion_id' => $faker->name,
		'wish_list' => $faker->name,
		'comments' => $faker->name
    ];
});