export default function (component) {
    let column_definition = [{
        "db_field": "id",
        "caption": "Id",
        "type": "link",
        "onClick": function (id) {
            component.$router.push(component.route + '/' + id)
        },
        "show_on_list": true,
        "show_on_view": true,
        "show_on_edit": true,
        "show_on_create": true,
        "th_width": "150px",
        "td_tags": "",
        "class": "",
        "events": [],
        "properties": [],
        "word_wrap": true,
        "post": true
    },
        {
            "db_field": "employee_id",
            "caption": "Employee Id",
            "type": "select",
            "placeholder": false,
            "select_values": component.data.employees,
            "show_on_list": true,
            "show_on_view": true,
            "show_on_edit": true,
            "show_on_create": true,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [],
            "search": "LIKE ANY BETWEEN EXACT",
            "properties": [],
            "word_wrap": true,
            "post": true
        }, {
            "db_field": "title",
            "caption": "Title",
            "type": "text",
            "show_on_list": true,
            "show_on_view": true,
            "show_on_edit": true,
            "show_on_create": true,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [],
            "search": "LIKE ANY BETWEEN EXACT",
            "properties": [],
            "word_wrap": true,
            "post": true
        }, {
            "db_field": "comments",
            "caption": "Comments",
            "type": "textarea",
            "show_on_list": true,
            "show_on_view": true,
            "show_on_edit": true,
            "show_on_create": true,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [],
            "search": "LIKE ANY BETWEEN EXACT",
            "properties": [],
            "word_wrap": true,
            "post": true
        }, {
            "db_field": "start_date",
            "caption": "Start Date",
            "type": "input",
            "placeholder": "YYYY-MM-DD",
            "show_on_list": true,
            "show_on_view": true,
            "show_on_edit": true,
            "show_on_create": true,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [],
            "search": "LIKE ANY BETWEEN EXACT",
            "properties": [],
            "word_wrap": true,
            "post": true
        },
        {
            "db_field": "start_time",
            "caption": "Start Time",
            "type": "input",
            "placeholder": "HH:MM 24, HH:MM p, HH:MM a",
            "show_on_list": true,
            "show_on_view": true,
            "show_on_edit": true,
            "show_on_create": true,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [],
            "properties": [],
            "word_wrap": true,
            "post": true
        }, {
            "db_field": "end_date",
            "caption": "Date End",
            "placeholder": "YYYY-MM-DD",
            "type": "input",
            "show_on_list": true,
            "show_on_view": true,
            "show_on_edit": true,
            "show_on_create": true,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [],
            "properties": [],
            "word_wrap": true,
            "post": true
        },
        {
            "db_field": "end_time",
            "caption": "End Time",
            "type": "input",
            "placeholder": "HH:MM 24, HH:MM p, HH:MM a",
            "show_on_list": true,
            "show_on_view": true,
            "show_on_edit": true,
            "show_on_create": true,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [],
            "properties": [],
            "word_wrap": true,
            "post": true
        },];

    return column_definition;
}