export default function (component, awesomeTable) {
    let column_definition = [{
        "db_field": "id",
        "caption": "Id",
        "type": "link",
        "onClick": function (id) {
            component.$router.push(component.route + '/' + id)
        },
        "show_on_list": true,
        "show_on_view": true,
        "show_on_edit": true,
        "show_on_create": true,
        "th_width": "150px",
        "td_tags": "",
        "class": "",
        "events": [],
        "properties": [],
        "word_wrap": true,
        "post": true
    },
        {
            "db_field": "employee_id",
            "caption": "Employee Id",
            "type": "select",
            "placeholder": false,
            "select_values": component.data.employees,
            "show_on_list": true,
            "show_on_view": true,
            "show_on_edit": true,
            "show_on_create": true,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [{"change":function(){
                let employee_id = awesomeTable.getValue('employee_id',0);
                let employee_name = awesomeTable.getSelectName('employee_id',employee_id);
                awesomeTable.setValue('title',0,'Shift: ' + employee_name);
            }}],

            "search": "LIKE ANY BETWEEN EXACT",
            "properties": [],
            "word_wrap": true,
            "post": true
        }, {
            "db_field": "title",
            "caption": "Title",
            "type": "text",
            "show_on_list": true,
            "show_on_view": true,
            "show_on_edit": true,
            "show_on_create": true,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [],
            "search": "LIKE ANY BETWEEN EXACT",
            "properties": [],
            "word_wrap": true,
            "post": true
        },  {
            "db_field": "start",
            "caption": "Start",
            "type": "text",
            "placeholder": "YYYY-MM-DD HH:MM 24 Hour Format (sorry!)",
            "show_on_list": true,
            "show_on_view": true,
            "show_on_edit": true,
            "show_on_create": true,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [],
            "search": "LIKE ANY BETWEEN EXACT",
            "properties": [],
            "word_wrap": true,
            "post": true
        },
        {
            "db_field": "end",
            "caption": "End",
            "placeholder": "YYYY-MM-DD HH:MM 24 Hour Format (sorry!)",
            "type": "text",
            "show_on_list": true,
            "show_on_view": true,
            "show_on_edit": true,
            "show_on_create": true,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [],
            "properties": [],
            "word_wrap": true,
            "post": true,
            "search": "LIKE ANY BETWEEN EXACT",

        },
        {
            "db_field": "hours",
            "caption": "Hours",
            "placeholder": "YYYY-MM-DD HH:MM 24 Hour Format (sorry!)",
            "type": "text",
            "show_on_list": true,
            "show_on_view": false,
            "show_on_edit": false,
            "show_on_create": false,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [],
            "properties": [],
            "word_wrap": true,
            'total':2,
            "post": true
        },
        {
            "db_field": "rate",
            "caption": "Est Pay Rate",
            "placeholder": "YYYY-MM-DD HH:MM 24 Hour Format (sorry!)",
            "type": "text",
            "show_on_list": true,
            "show_on_view": false,
            "show_on_edit": false,
            "show_on_create": false,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [],
            "properties": [],
            "word_wrap": true,
            "post": true
        },
        {
            "db_field": "pay",
            "caption": "Estimated Pay",
            "type": "text",
            "show_on_list": true,
            "show_on_view": false,
            "show_on_edit": false,
            "show_on_create": false,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [],
            "properties": [],
            "word_wrap": true,
            'total':2,
            "post": true
        },
        {
            "db_field": "comments",
            "caption": "Comments",
            "type": "textarea",
            "show_on_list": true,
            "show_on_view": true,
            "show_on_edit": true,
            "show_on_create": true,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [],
            "search": "LIKE ANY BETWEEN EXACT",
            "properties": [],
            "word_wrap": true,
            "post": true
        },
      ];

    return column_definition;
}