export default function(component){
    let column_definition = [
        {
            "db_field": "id",
            "caption": "Id",
            "type": "link",
            "onClick":  function(id){
                component.$router.push(component.route + '/' + id)
            },
            "placeholder": false,
            "route": "terminals",
            "show_on_list": true,
            "show_on_view": true,
            "show_on_edit": true,
            "show_on_create": true,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [],
            "search": "LIKE ANY BETWEEN EXACT",
            "search_default": "",
            "properties": [],
            "word_wrap": true,
            "post": true
        }, {
            "db_field": "name",
            "caption": "Name",
            "type": "text",
            "placeholder": false,
            "route": "terminals",
            "select_values": "use with select",
            "default_value": "default value is set",
            "show_on_list": true,
            "show_on_view": true,
            "show_on_edit": true,
            "show_on_create": true,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [],
            "search": "LIKE ANY BETWEEN EXACT",
            "search_default": "",
            "properties": [],
            "word_wrap": true,
            "post": true
        },  {
            "db_field": "status",
            "caption": "Status",
            "type": "select",
            "placeholder": false,
            "route": "terminals",
            "select_values": [{'value':'open','name':'Open'},{'value':'closed','name':'Closed'},{'value':'locked','name':'Locked'}],
            "default_value": "open",
            "show_on_list": true,
            "show_on_view": true,
            "show_on_edit": true,
            "show_on_create": true,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [],
            "search": "LIKE ANY BETWEEN EXACT",
            "search_default": "",
            "properties": [],
            "word_wrap": true,
            "post": true
        },  {
            "db_field": "description",
            "caption": "Description",
            "type": "textarea",
            "placeholder": false,
            "select_values": "use with select",
            "default_value": "default value is set",
            "show_on_list": true,
            "show_on_view": true,
            "show_on_edit": true,
            "show_on_create": true,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [],
            "search": "LIKE ANY BETWEEN EXACT",
            "search_default": "",
            "properties": [],
            "word_wrap": true,
            "post": true
        }, {
            "db_field": "active",
            "caption": "Active",
            "type": "checkbox",
            "placeholder": false,
            "route": "terminals",
            "select_values": "use with select",
            "default_value": "default value is set",
            "show_on_list": true,
            "show_on_view": true,
            "show_on_edit": true,
            "show_on_create": true,
            "th_width": "150px",
            "td_tags": "",
            "class": "",
            "events": [],
            "search": "LIKE ANY BETWEEN EXACT",
            "search_default": "",
            "properties": [],
            "word_wrap": true,
            "post": true
        }, ];

    return column_definition;
}